name: TransLiG
channels:
  - biobuilds
  - defaults
  - conda-forge
  - bioconda
  - defaults
  - conda-forge/label/broken
  - conda-forge/label/noarch
  - bioconda/label/cf201901
  - bioconda/label/noarch
dependencies:
  - python=3.7.0
  - boost=1.70.0
  - libgcc-ng=7.3.0
  - libstdcxx-ng=7.3.0
  - translig=1.3.0
  - fastool
  - seqtk
  - seqkit
